delete from role;
delete from user;
delete from user_favorites;
delete from notes;
delete from crops;
delete from item;
delete from item_type;
INSERT INTO `item` VALUES (1, 'blue jazz', 'crop'),(2, 'cauliflower', 'crop'),(3, 'garlic', 'crop'),(4, 'salmonberry', 'forage'),(5, 'milk', 'animal product'),(6, 'strawberry', 'crop'),(7, 'cheese cauliflower', 'recipe');
INSERT INTO `item_type` VALUES (3,'animal product'),(1,'crop'),(4,'fish'),(2,'forage'),(5,'recipe');
INSERT INTO `user` VALUES (1,'user1','password'),(2,'user2','password'),(3,'user3','password');
INSERT INTO `crops` VALUES (1,3,'Spring',80,175,'Escargot, Fiddlehead Rissoto','None');
INSERT INTO `user_favorites` VALUES (1,1,1),(2,1,6),(3,2,7),(4,3,2),(5,1,3),(6,3,1);
INSERT INTO `notes` VALUES (1,2,2,'Need 2 more gold for bundle'),(2,1,1,'lucky lunch'),(3,2,6,'cant buy seeds til spring 13'),(4,2,6,'save seeds for next spring');
INSERT INTO `role` VALUES (1,'admin','user1', 1);
